-- =========================
-- V17__fix_test_patient_user.sql
-- Fix or create test patient user with correct password hash
-- =========================

-- Test patient credentials:
-- Phone: +998901234567 or email: patient@test.com
-- Password: patient123

-- Delete existing test patient user if exists (to recreate with correct hash)
-- Note: This migration creates/updates the user via application code, not SQL
-- The actual password hash needs to be generated by BCryptPasswordEncoder
-- Use the /api/test/create-test-patient endpoint after this migration runs

-- Update patient profile to ensure it exists and is linked properly
UPDATE patient_profiles
SET 
  full_name = 'Test Patient',
  email = 'patient@test.com',
  phone = '+998901234567',
  address = 'Tashkent, Uzbekistan',
  birth_date = '1990-01-01',
  language = 'Uzbek'
WHERE phone = '+998901234567' OR email = 'patient@test.com';

-- Insert patient profile if it doesn't exist
INSERT INTO patient_profiles (full_name, phone, email, address, birth_date, language)
SELECT 
  'Test Patient',
  '+998901234567',
  'patient@test.com',
  'Tashkent, Uzbekistan',
  '1990-01-01',
  'Uzbek'
WHERE NOT EXISTS (
  SELECT 1 FROM patient_profiles WHERE phone = '+998901234567' OR email = 'patient@test.com'
);
